### PR TITLE
Dev branch

### PR DESCRIPTION
**Pull request by LuisSalas94**
In this branch:

Added index.html
Added styles.css
Added test.md
Modified .gitignore
Fixed linters errors

### CODE REVIEW

**Review by Hamzaoutdoors — CHANGES_REQUESTED** [review]
Hi @LuisSalas94, I am **Hamza** your reviewer for this PR 😸 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

image

## Required Changes ♻️

- [ ] Please kindly, add a descriptive title and description for this pull request explaining what you did in this branch
```
In this branch :
 - Added ...
 - Added ...
 - Added ...
 - Fixed ...
- Created a README.md file. 
etc
```

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
( - **N.A.** )


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by LuisSalas94** [comment]
In this branch:
- Added index.html
- Added styles.css
- Added test.md
- Modified .gitignore
- Fixed linters errors

**Comment by LuisSalas94** [comment]
Are these descriptions and titles correct?

**Review by ReshyResh — APPROVED** [review]
# Hi @LuisSalas94 ,

### You did a good job with your first project. For the next time please add a meaningful title for the pull request as well besides the description. Something like `Hello Microverse - First milestone` or anything along those lines would be perfect!

### Congratulations, your project is approved! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

**Pull request merged**
